---
format: pdf
---


```{r}
library(ggplot2)
library(tibble)
```


```{r}
#Question 2

set.seed(301)
generate_data <- function(i = 1000) {
  data <- tibble( party = sample(0:1, i, replace = TRUE),
      age = sample(c('18-24', '25-34', '35-44', '45-54', '55+'), i, replace = TRUE),
      gender = sample(c('Male', 'Female'), i, replace = TRUE),
      income = sample(c('Low', 'Medium', 'High'), i, replace = TRUE),
      education = sample(c('High School', 'Bachelor', 'Master', 'Doctorate'), i, replace = TRUE)
      )
return(data)
}

sim_data <- generate_data(1000)
sim_data
```
```{r}
set.seed(302)
generate_data(1000)
```

```{r}
set.seed(303)
generate_data(1000)
```

```{r}
set.seed(304)
generate_data(1000)
```

```{r}
set.seed(305)
generate_data(1000)
```

```{r}
set.seed(306)
generate_data(1000)
```

```{r}
set.seed(307)
generate_data(1000)
```

```{r}
set.seed(308)
generate_data(1000)
```

```{r}
set.seed(309)
generate_data(1000)
```

```{r}
set.seed(300)
generate_data(1000)
```




